# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

	Anredewert.create! :id => 0, :wert => ""
    Anredewert.create! :id => 1, :wert => "Herr"
    Anredewert.create! :id => 2, :wert => "Frau"
    Anredewert.create! :id => 3, :wert => "Familie"
    Anredewert.create! :id => 4, :wert => "Firma"

	Geschlechtswert.create! :id => 0, :wert => ""
	Geschlechtswert.create! :id => 1, :wert => "m"
	Geschlechtswert.create! :id => 2, :wert => "mk"
	Geschlechtswert.create! :id => 3, :wert => "w"
	Geschlechtswert.create! :id => 4, :wert => "wk"

	Kontaktwert.create! :id => 0, :wert => ""
	Kontaktwert.create! :id => 1, :wert => "Telefon"
	Kontaktwert.create! :id => 2, :wert => "Fax"
	Kontaktwert.create! :id => 3, :wert => "Email"

	Impfungswert.create! :id => 1, :wert => "RCP"
	Impfungswert.create! :id => 2, :wert => "Leukose"
	Impfungswert.create! :id => 3, :wert => "FIP"
	Impfungswert.create! :id => 4, :wert => "TW"
	Impfungswert.create! :id => 5, :wert => "SP"
	Impfungswert.create! :id => 6, :wert => "SHLP"
	Impfungswert.create! :id => 7, :wert => "SHLPPi"
	Impfungswert.create! :id => 8, :wert => "SHLPPiT"
	Impfungswert.create! :id => 9, :wert => "Borreliose"
	Impfungswert.create! :id => 10, :wert => "Bpi"
	Impfungswert.create! :id => 11, :wert => "Myxo"
	Impfungswert.create! :id => 12, :wert => "RHD"
	Impfungswert.create! :id => 13, :wert => "Leptospir"
	
	# Katze
	Laborwert.create! :tierart => 1, :sortkey => 0, :wert => "***KATZE***"
	Laborwert.create! :tierart => 1, :sortkey => 1, :wert => "Gluc (71-148)"
	Laborwert.create! :tierart => 1, :sortkey => 2, :wert => "Bun (17-33)"
	Laborwert.create! :tierart => 1, :sortkey => 3, :wert => "Crea (0,8-1,8)"
	Laborwert.create! :tierart => 1, :sortkey => 4, :wert => "Phos (2,6-6)"
	Laborwert.create! :tierart => 1, :sortkey => 5, :wert => "GPT (22-84)"
	Laborwert.create! :tierart => 1, :sortkey => 6, :wert => "GOT (18-51)"
	Laborwert.create! :tierart => 1, :sortkey => 7, :wert => "Bil (0,1-0,4)"
	Laborwert.create! :tierart => 1, :sortkey => 8, :wert => "ALP (38-165)"
	Laborwert.create! :tierart => 1, :sortkey => 9, :wert => "Amyl (200-1900)"
	Laborwert.create! :tierart => 1, :sortkey => 10, :wert => "CK (97-309)"
	Laborwert.create! :tierart => 1, :sortkey => 11, :wert => "K (3,4-4,6)"
	Laborwert.create! :tierart => 1, :sortkey => 12, :wert => "TP (5,7-7,8)"
	Laborwert.create! :tierart => 1, :sortkey => 13, :wert => "T4 (13-50)"
	Laborwert.create! :tierart => 1, :sortkey => 14, :wert => "WBC (5-11)"
	Laborwert.create! :tierart => 1, :sortkey => 15, :wert => "RBC (5-10)"
	Laborwert.create! :tierart => 1, :sortkey => 16, :wert => "HK (27-47)"
	Laborwert.create! :tierart => 1, :sortkey => 17, :wert => "Hb (8-17)"
	Laborwert.create! :tierart => 1, :sortkey => 18, :wert => "Gran (3-12)"
	Laborwert.create! :tierart => 1, :sortkey => 18, :wert => "Lym (1-4)"
	Laborwert.create! :tierart => 1, :sortkey => 20, :wert => "Mon (0-0,5)"
	Laborwert.create! :tierart => 1, :sortkey => 21, :wert => "PLT (180-430)"
	Laborwert.create! :tierart => 1, :sortkey => 22, :wert => "Ka (3,4-4,6)"
	Laborwert.create! :tierart => 1, :sortkey => 23, :wert => "Na (147-156)"
	Laborwert.create! :tierart => 1, :sortkey => 24, :wert => "Cl (107-120)"

	# Hund
	Laborwert.create! :tierart => 2, :sortkey => 50, :wert => "***HUND***"
	Laborwert.create! :tierart => 2, :sortkey => 51, :wert => "Gluc (75-128)"
	Laborwert.create! :tierart => 2, :sortkey => 52, :wert => "Bun (9-29)"
	Laborwert.create! :tierart => 2, :sortkey => 53, :wert => "Crea (0,4-1,4)"
	Laborwert.create! :tierart => 2, :sortkey => 54, :wert => "Phos (1,9-5)"
	Laborwert.create! :tierart => 2, :sortkey => 55, :wert => "GPT (17-78)"
	Laborwert.create! :tierart => 2, :sortkey => 56, :wert => "GOT (17-44)"
	Laborwert.create! :tierart => 2, :sortkey => 57, :wert => "GGT (5-14)"
	Laborwert.create! :tierart => 2, :sortkey => 58, :wert => "Bil (0,1-0,5)"
	Laborwert.create! :tierart => 2, :sortkey => 59, :wert => "ALP (47-254)"
	Laborwert.create! :tierart => 2, :sortkey => 60, :wert => "Amyl (200-1400)"
	Laborwert.create! :tierart => 2, :sortkey => 61, :wert => "CK (49-166)"
	Laborwert.create! :tierart => 2, :sortkey => 62, :wert => "K (3,8-5,0)"
	Laborwert.create! :tierart => 2, :sortkey => 63, :wert => "TP (5,0-7,2)"
	Laborwert.create! :tierart => 2, :sortkey => 64, :wert => "WBC (6-12)"
	Laborwert.create! :tierart => 2, :sortkey => 65, :wert => "RBC (6-9)"
	Laborwert.create! :tierart => 2, :sortkey => 66, :wert => "HK (40-55)"
	Laborwert.create! :tierart => 2, :sortkey => 67, :wert => "Hb (15-19)"
	Laborwert.create! :tierart => 2, :sortkey => 68, :wert => "Gran (1,2-6,8)"
	Laborwert.create! :tierart => 2, :sortkey => 69, :wert => "Lym (1,2-3,2)"
	Laborwert.create! :tierart => 2, :sortkey => 70, :wert => "Mon (0,3-0,8)"
	Laborwert.create! :tierart => 2, :sortkey => 71, :wert => "PLT (150-500)"
	Laborwert.create! :tierart => 2, :sortkey => 72, :wert => "Ka (3,8-5,0)"
	Laborwert.create! :tierart => 2, :sortkey => 73, :wert => "Na (141-152)"
	Laborwert.create! :tierart => 2, :sortkey => 74, :wert => "Cl (102-117)"

	# Kaninchen
	Laborwert.create! :tierart => 3, :sortkey => 100, :wert => "***KANINCHEN***"
	Laborwert.create! :tierart => 3, :sortkey => 101, :wert => "Leukos (5-12)"
	Laborwert.create! :tierart => 3, :sortkey => 102, :wert => "HK (33-48)"
	Laborwert.create! :tierart => 3, :sortkey => 103, :wert => "Gluc (115-214)"
	Laborwert.create! :tierart => 3, :sortkey => 104, :wert => "Bun (11-28)"
	Laborwert.create! :tierart => 3, :sortkey => 105, :wert => "Crea (0,6-1,4)"
	Laborwert.create! :tierart => 3, :sortkey => 106, :wert => "GPT (12-72)"
	Laborwert.create! :tierart => 3, :sortkey => 107, :wert => "GGT (5-18)"
	Laborwert.create! :tierart => 3, :sortkey => 108, :wert => "Bil (0,1-0,4)"
	Laborwert.create! :tierart => 3, :sortkey => 109, :wert => "ALP (21-75)"
	Laborwert.create! :tierart => 3, :sortkey => 110, :wert => "TP (4,9-6,9)"
	Laborwert.create! :tierart => 3, :sortkey => 111, :wert => "Calc (12,-14,5)"
